name: Test, Build, and release
on:
  push:
    branches:
      - main
      - master
permissions:
  actions: read
  checks: read
  contents: write
  deployments: write
  issues: write
  packages: write
  pages: write
  statuses: write

jobs:
  test:
    name: Lint and test on Node ${{ matrix.node }} and ${{ matrix.os }}

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        node: ['16.x', '18.x']
        os: 
          - ubuntu-latest
          # - windows-latest
          # - macOS-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Use Node ${{ matrix.node }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}
          cache: 'npm'

      - name: Install dependencies 📦
        run: npm run install

      - name: Lint 🔍
        run: npm run lint

      - name: Test 🧪
        run: npm run test

      - name: Build 🏗
        # run: npm run prepare
        run: npm run build


  release:
    name: Release 🚚
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Use Node
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'npm'
          registry-url: https://npm.pkg.github.com
          always-auth: true
          scope: '@hudora'
    
      - name: Install dependencies 📦
        # run: echo "//npm.pkg.github.com/:_authToken=${{ secrets.NODE_AUTH_TOKEN }}" >> ~/.npmrc
        run: npm run install 

      - name: Build 🏗
        # run: npm run prepare
        run: npm run build

      - name: Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: npx semantic-release

      # - name: Deploy storybook to GitHub Pages
      #   run: npm run run storybook-deploy --ci
      #   env:
      #       GH_TOKEN: ${{ github.actor }}:${{ secrets.GITHUB_TOKEN }}